steps:
- id: compile
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - '-c'
  - |
    mvn compile


- id: Build
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - '-c'
  - |
    mvn package -DskipTests=true

# - id: sonar-analysis
#   name: maven:3.9.9-amazoncorretto-17
#   entrypoint: sh
#   args:
#   - '-c'
#   - |
#     mvn sonar:sonar \
#     -Dsonar.projectKey=your_project_key \
#     -Dsonar.host.url=https://e6d5-102-159-9-76.ngrok-free.app \
#     -Dsonar.login=squ_195add6ef78c7b220ff262619cf295a153138649

- id: Docker Build
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t just_for_testing:${SHORT_SHA} .
options:
  logging: CLOUD_LOGGING_ONLY
