steps:
- id: compile
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - '-c'
  - |
    mvn compile


- id: Build
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - '-c'
  - |
    mvn package -DskipTests=true

- id: Docker Build
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t Just_for_testing:${SHORT_SHA} .

options:
  logging: CLOUD_LOGGING_ONLY