steps:
- id: mvn-compile
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - -c
  - |
    mvn compile
- id: mvn-Build
  name: maven:3.3-jdk-8
  entrypoint: sh
  args:
  - -c
  - |
    mvn package -DskipTests=true
- id: Docker-build-push-artifact-registry
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    docker build -t europe-west1-docker.pkg.dev/aidodev/pi-gen-testing2/app:latest .
    docker push europe-west1-docker.pkg.dev/aidodev/pi-gen-testing2/app:latest
- id: Cloudrun-artifact-registry
  name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  args:
  - -c
  - |-
    echo "***************************"
    echo europe-west1-docker.pkg.dev/aidodev/pi-gen-testing2/app:latest
    echo "***************************"

    gcloud run deploy java-test \
    --region=europe-west1 \
    --image=europe-west1-docker.pkg.dev/aidodev/pi-gen-testing2/app:latest
    --set-secrets=REDIS_HOST=REDIS_HOST_DEV:latest
options:
  logging: CLOUD_LOGGING_ONLY
